### ISSUE TITLE
The "Prevent loss of honor" setting

### ISSUE THREAD

**Issue by Sakoke-21** [darkbot-reloaded/DarkBot#375] opened 2024-08-20 14:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you running the latest bot version?

- [X] I have confirmed i'm running the latest bot version

### Have you tried to remove all plugins and see if the issue persists?

- [X] I have reproduced the issue even after removing all non-required plugins

### Can anyone else reproduce the issue?

- [X] I have confirmed with someone else that they can reproduce the issue too.

### Describe the bug

The "Prevent loss of honor" setting does not work. Even though I closed it, it says "signed out, loss of honor".

### Steps To Reproduce

1. I started the bot and activated the "Hitac" configuration.
2. I activated "Defense Mode" in DmPlugin.
3. I've arranged for him to help if anyone attacks my group.
4.I set it to hit even if it's the same ally.
5.I identified the problem and contacted support. I couldn't get any information so I researched and found it myself.
6.I turned off the "prevent loss of honor" setting and thought the problem would be fixed.
7.But it didn't work, it logged out again.

### Screenshots, Video, or other media

![setting](https://github.com/user-attachments/assets/246e3f0c-45f5-4ab7-a3f6-ef083f13dbb3)
![signed out, loss of honor](https://github.com/user-attachments/assets/2de0d09d-3c2e-41e4-8b8b-9b577701391d)

### Logs

[2024-08-20_14-02-57_166.log](https://github.com/user-attachments/files/16677008/2024-08-20_14-02-57_166.log)
[2024-08-20_14-03-02_KekkaPlayer.log](https://github.com/user-attachments/files/16677010/2024-08-20_14-03-02_KekkaPlayer.log)
[2024-08-20_15-56-33_301.log](https://github.com/user-attachments/files/16677014/2024-08-20_15-56-33_301.log)
[2024-08-20_15-56-35_KekkaPlayer.log](https://github.com/user-attachments/files/16677015/2024-08-20_15-56-35_KekkaPlayer.log)

### Bot Version

v 1.131.2

### Installed Plugins & versions

Darkplane v1.22.0
Default plugin v2.0.0
DmPlugin v2.2.14
Donor plugin v2.2.4
Kekka Reloaded v1.6.9
KEKW v1.7.0
!LeanPlugin v1.6.6
MiniCore v1.6.2
Optimal v1.0.9
Osiris v1.6.1
Penguin Plugin v3.4.0
Pika Plugin v1.8.23
REEE v2.0.1
Ruski Plugin v1.2.12
TYX Plugin v1.2.7
VoT Plugin v1.2.4

### Browser API & version

KekkaPlayer v26

### Operating System

Win10

**Comment by Pablete1234** [comment] 2024-08-20 16:43
There is no setting to not prevent stopping on honor lost. The setting is only to decide if an exact number of honor lost is required to detect it as honor lost. In other words: if we should be more strict in what is considered an honor lost, in order to avoid random memory read issues from causing it to stop.

Unsure what the translation is, but in english i think it's pretty self explainatory:
"Prevent pausing on random honor lost"
"Only pause bot on honor lost if the lost amount is an exact number from a kill"



Closing as works as intended

**Closed by Pablete1234** 2024-08-20 16:43 UTC
Labels: bug
